### ISSUE TITLE
Ready for Review

### ISSUE THREAD

**Issue by jmaldia** [dalumiller/Udacity-Documentation-Group-Project#3]
Add a link to your Repo here and @ the reviewers

**Comment by jeneesmith1** [comment]
You can @jeneesmith1 on Github or @jeneecsmith on Udacity to request your content review!

**Comment by mjbeauchamp** [comment]
Thanks for the help!

https://github.com/mjbeauchamp/Udacity-Documentation-Group-Project/tree/reduceMethod

@jeneesmith1 @jmaldia

**Comment by jmaldia** [comment]
@mjbeauchamp The code looks good. I have a couple of thoughts that are not vital. 

1. When you introduced this code, maybe you can explain what `arr` is. 
   ```
arr.reduce(function(accumulator, currentValue, currentIndex, array){
	  //Callback code
});
```
2. For examples, maybe have one as the first example a basic summation of the array.
