### ISSUE TITLE
No syntax highlighting for code examples

### ISSUE THREAD

**Issue by tyler-vs** [dalumiller/Udacity-Documentation-Group-Project#6]
Perhaps not a priority until more content is added, but I think it would be beneficial to add some form of syntax highlighting for the code examples, this may bring about another issue of having a means to serve a site locally for development.

**Comment by jmaldia** [comment]
@dalumiller @tyler-vs I have a solution for this. I'll work on it tomorrow and issue a PR.

**Comment by jmaldia** [comment]
I was going to add prism.js and it looks like it's already in there. LOL. I guess we just need to implement it.

**Comment by jmaldia** [comment]
made a PR: https://github.com/dalumiller/Udacity-Documentation-Group-Project/pull/14

**Comment by tyler-vs** [comment]
@jmaldia yup, prism assets were added to the template file, thank you for adding an examples on how to use it.
